smash> smash> smash> smash> smash> smash> smash> smash> smash> smash> smash> smash> smash> smash> signal number 9 was sent to pid 2
smash> smash: got ctrl-C
smash> smash> smash> smash: got ctrl-C
smash> [1] sleep 7&
smash> smash> [1] sleep 7&
[2] sleep 5&
smash> smash> smash: got ctrl-C
[1] sleep 7&
[2] sleep 5&
[3] sleep 3&
smash> smash> smash> smash: got ctrl-C
[1] sleep 7&
[2] sleep 5&
[3] sleep 3&
smash> smash> smash: got ctrl-C
[1] sleep 7&
[2] sleep 5&
[3] sleep 3&
[4] sleep 10 &
smash> signal number 9 was sent to pid 3
smash> smash: got ctrl-C
[2] sleep 5&
[3] sleep 3&
[4] sleep 10 &
smash> smash> smash: got ctrl-C
smash> smash: got ctrl-C
smash: got ctrl-C
smash: process 4 was killed
smash> smash: got ctrl-C
[2] sleep 5&
[4] sleep 10 &
[5] sleep 5&
[6]           sleep        10   &
smash> smash> smash: got ctrl-C
[2] sleep 5&
[4] sleep 10 &
[5] sleep 5&
[6]           sleep        10   &
smash> signal number 9 was sent to pid 5
smash> smash: got ctrl-C
[4] sleep 10 &
[5] sleep 5&
[6]           sleep        10   &
smash> smash> smash: got ctrl-C
[4] sleep 10 &
[5] sleep 5&
[6]           sleep        10   &
smash> smash> smash: got ctrl-C
smash: process 6 was killed
smash> smash: got ctrl-C
smash> smash: got ctrl-C
smash: sending SIGKILL signal to 4 jobs:
7: sleep 10 &
8: sleep 5&
9:           sleep        10   &
10: sleep 20&
