smash error: execvp failed: No such file or directory
smash error: fg: job-id 12 does not exist
smash error: fg: job-id 12 does not exist
smash error: fg: job-id 12 does not exist
smash error: fg: job-id 11 does not exist
smash error: fg: job-id 11 does not exist
smash error: fg: job-id 20 does not exist
smash error: fg: job-id 21 does not exist
smash error: fg: job-id -2 does not exist
smash error: execvp failed: No such file or directory
smash error: execvp failed: No such file or directory
smash error: execvp failed: No such file or directory
smash error: execvp failed: No such file or directory
smash error: execvp failed: No such file or directory
smash error: kill: job-id 1 does not exist
smash error: fg: job-id 4 does not exist
smash error: execvp failed: No such file or directory
smash error: fg: job-id 1 does not exist
smash error: execvp failed: No such file or directory
